version: '3.4'

services:
  db:
    image: mysql:latest 
    container_name: db_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db_sql:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db_sql:3306/clean_database
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db_sql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    volumes:
      - .:/app